### ISSUE TITLE
Bulk Sending Issue

### ISSUE THREAD

**Issue by TheSeaEmperor** [bsergent/RealMail#14]
I was wondering, with the Bulk Sending of mail, could you make it so everyone can claim the item off the mail because as of right now, only one person is able to claim the item off a bulk sent mail.

**Comment by bsergent** [comment]
Yep, I don't know why I never noticed this before, but it'll be fixed by the next update. Thank you for using the issue tracker!

**Comment by bsergent** [comment]
Tested and confirmed as fixed, will be released with v0.3.3.
